create database sensors_db;

create table users
(
    id       integer generated by default as identity
        constraint person_pkey
            primary key,
    username varchar(100) not null,
    password varchar(100) not null,
    role     varchar(20) CHECK (role = 'ROLE_USER' or role = 'ROLE_ADMIN')
);

CREATE TABLE types
(
    id   integer generated by default as identity primary key,
    name varchar(20)
);
CREATE TABLE units
(
    id   integer generated by default as identity primary key,
    name varchar(20)
);
CREATE TABLE sensors
(
    id          integer generated by default as identity primary key,
    title       VARCHAR(30),
    model       VARCHAR(15),
    range_from  int NOT NULL,
    range_to    int NOT NULL,
    type_id     INT NOT NULL,
    unit_id     INT,
    location    VARCHAR(40),
    description VARCHAR(200),
    CONSTRAINT FK_sensors_types FOREIGN KEY (type_id)
        REFERENCES types (id),
    CONSTRAINT FK_sensors_units FOREIGN KEY (unit_id)
        REFERENCES units (id)

);

INSERT INTO types(name)
VALUES ('Pressure'),
       ('Voltage'),
       ('Temperature'),
       ('Humidity');

INSERT INTO units(name)
VALUES ('bar'),
       ('voltage'),
       ('°С'),
       ('%');

INSERT INTO users(username, password, role)
VALUES ('Anna09', '$2a$10$IjCmYrkHeVMft9bBAvOvoO0cekPNaPz.WWOYgV4EJ9aiZTofoPOZu', 'ROLE_ADMIN');

INSERT INTO sensors(title, model, range_from, range_to, type_id, unit_id, location, description)
VALUES ('barometer', 'ac-23', 22, 45, 1, 1, 'kitchen', 'some description'),
       ('thermometer', 'al-2f', -10, 50, 3, 3, 'bedroom', 'some description'),
       ('multimeter', 'acl-56', 0, 70, 2, 2, 'room', 'some description'),
       ('voltmeter', '7823', 10, 30, 2, 2, 'room', 'some description'),
       ('psychrometer', 'jn087', 0, 100, 4, 4, 'yard', 'some description'),
       ('barometer', 'ac-24', 20, 48, 1, 1, 'kitchen', 'some description'),
       ('hygrometer', '07gh', 0, 100, 4, 4, 'yard', 'some description'),
       ('manometer', 'al-23', 18, 42, 1, 1, 'hall', 'some description'),
       ('thermometer', 'al-21', -10, 50, 3, 3, 'bedroom', 'some description'),
       ('barometer', 'am-23', 21, 73, 1, 1, 'kitchen', 'some description'),
       ('multimeter', '78-dh', 5, 65, 2, 2, 'room', 'some description'),
       ('barometer', 'ac-23', 22, 45, 1, 1, 'kitchen', 'some description'),
       ('voltmeter-12', '78kl', 10, 30, 2, 2, 'room', 'some description'),
       ('psychrometer-23', 'hu-78', 0, 100, 4, 4, 'yard', 'some description'),
       ('barometer', 'ac-27', 22, 45, 1, 1, 'kitchen', 'some description');

